name: Windows Workflow

on:
workflow_dispatch:

jobs:
build:
name: Start Building
runs-on: windows-latest

```
steps:
  - name: Checkout Repository
    uses: actions/checkout@v4

  - name: Print Message
    run: echo Workflow started successfully

  - name: Create Test Script
    run: |
      echo echo Hello from batch file > test.bat

  - name: Run Test Script
    run: cmd /c test.bat

  - name: List Files
    run: dir
```
